Allow empty strings.
stjohnjohnson/shell-variables pull request #4
Opened 2016-12-03 03:28 UTC by jacobtolar

Before this change, you get an error if you've explicitly set a value to empty and later try to retrieve it.

2016-12-03 03:58 UTC, jacobtolar commented
The build failure seems to be due to dependency version changes? 

If I pin `request` to 2.75.0 all tests pass. On 2.76.0 a few fail. Not sure what the deeper issue is... 

https://github.com/request/request/compare/v2.75.0...v2.76.0

Installing 2.76.0 dep from 2.75.0 gives me:
```
- core-util-is@1.0.2 node_modules/core-util-is
- isarray@1.0.0 node_modules/isarray
- process-nextick-args@1.0.7 node_modules/process-nextick-args
- string_decoder@0.10.31 node_modules/string_decoder
- util-deprecate@1.0.2 node_modules/util-deprecate
- readable-stream@2.0.6 node_modules/readable-stream
- bl@1.1.2 node_modules/bl
shell-variables@1.2.0 /src/shell-variables
└─┬ request@2.76.0
  ├── form-data@2.1.2
  └── qs@6.3.0
```

2016-12-05 15:39 UTC, jacobtolar commented
Found it; https://github.com/request/request/pull/2431 changes the timeout to happen on socket connect, not request.start()

Updated the request dependency to include this change, and updated nock to be able to use the [socket timeout](https://github.com/node-nock/nock#socket-timeout) feature.

2016-12-19 23:27 UTC, stjohnjohnson requested changes

2016-12-19 23:27 UTC, stjohnjohnson commented on lib/client.js
> +        if (!error && response.statusCode === 200 && (body.value || body.value === "")) {
Didn't realize this, doesn't this mean `0` and `false` are also going to fail?  Can we change this to `body.value !== undefined`

2016-12-19 23:27 UTC, stjohnjohnson commented on package.json
> +    "request": "2.76.0"
So the intention is to pin to 2.76 now?  Just to be clear.

2016-12-19 23:27 UTC, stjohnjohnson commented
Sorry for the delay, just some quick questions.

2016-12-19 23:32 UTC, jacobtolar commented on package.json
> +    "request": "2.76.0"
Oh, whoops. That was from some testing. I'll change it to '^2.76.0'.

2016-12-19 23:32 UTC, jacobtolar commented on lib/client.js
> +        if (!error && response.statusCode === 200 && (body.value || body.value === "")) {
Sure, that makes sense.

2016-12-20 07:06 UTC, stjohnjohnson approved these changes
![yes](https://cloud.githubusercontent.com/assets/622065/21341144/d1393266-c63f-11e6-9fa3-e180094768a8.gif)

2016-12-20 07:07 UTC, merged

2016-12-20 07:08 UTC, stjohnjohnson commented
+ shell-variables@1.3.0

2016-12-23 00:59 UTC, jacobtolar commented
thanks!